---
title: "simple_aerosol_model2"
output: html_document
date: "2025-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(terra)
library(sf)

r <- rast("GLM_gridded/2024-07-03-gridded.nc")

# dimensions should be 5424 x 5424 (from your file)
nrows <- 5424
ncols <- 5424

# create a new raster with correctr geometry
r_fixed <- rast(
  nrows = nrows,
  ncols = ncols,
  xmin  = -5434895,
  xmax  =  5434895,
  ymin  = -5434895,
  ymax  =  5434895,
  crs   = "+proj=geos +lon_0=-75 +h=35786023 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +sweep=x"
)

# copy over the values from the original raster
values(r_fixed) <- values(r)

aod <- rast("MERRA2_400.inst3_2d_gas_Nx.20240703.nc4")

r_aod = aod[[1]]
for (i in 2:8) {
  r_aod = r_aod + aod[[i]]
}
crs(r_aod) <- "EPSG:4326"
lightning_proj <- project(r_fixed, r_aod, method = "near")

cape <- mean(rast("cape_era5.nc"))
crs(cape) <- "EPSG:4326"
cape_proj <- project(cape, r_aod)

aod <- rast("MERRA2_400.tavg1_2d_aer_Nx.20240703.nc4")
crs(aod) <- "EPSG:4326"
bc <- mean(subset(aod, grep("^BCEXTTAU", names(aod), value = TRUE)))
du <- mean(subset(aod, grep("^DUEXTTAU", names(aod), value = TRUE)))
ss <- mean(subset(aod, grep("^SSEXTTAU", names(aod), value = TRUE)))
oc <- mean(subset(aod, grep("^OCEXTTAU", names(aod), value = TRUE)))
so <- mean(subset(aod, grep("^SUEXTTAU", names(aod), value = TRUE)))

bc_proj <- project(bc, r_aod)
du_proj <- project(du, r_aod)
ss_proj <- project(ss, r_aod)
oc_proj <- project(oc, r_aod)
so_proj <- project(so, r_aod)
```

Convert data to dataframe

```{r}
both <- c(lightning_proj, r_aod, cape_proj,
          bc_proj, du_proj, ss_proj,
          oc_proj, so_proj)
df <- as.data.frame(both, na.rm = T, xy = T)
colnames(df) <- c("x", "y", "lightning", "aod", "cape",
                  "bc", "du", "ss", "oc", "so")
df_nozero <- df[df$lightning != 0,]
```

Let's subset to CONUS

```{r}
df_conus <- df_nozero[df_nozero$x > -129 & df_nozero$x < -66 & df_nozero$y > 24 & df_nozero$y < 50,]
```

Basis linear regression

```{r}
plot(df_conus$aod, df_conus$lightning,
     ylab = "Number of Lightning Strikes",
     xlab = "Total AOD",
     col = adjustcolor("black", alpha.f = 0.1), 
     pch = 19, cex = 0.5)

```

```{r}
plot(df_nozero$aod, df_nozero$cape,
     ylab = "Number of Lightning Strikes",
     xlab = "AOD",
     col = adjustcolor("black", alpha.f = 0.1), 
     pch = 19, cex = 0.5)#,
     # xlim = c(0,2), ylim = c(0,100))

```


```{r}
plot(tapply(df_conus$aod, df_conus$lightning, FUN = mean), 
     xlab = "Lightning Strikes", ylab = "Average AOD",
     col = adjustcolor("black", alpha.f = 0.5),
     pch = 19)
```

```{r}
plot(tapply(df_conus$cape, df_conus$lightning, FUN = mean), 
     xlab = "Lightning Strikes", ylab = "Average CAPE",
     col = adjustcolor("black", alpha.f = 0.5),
     pch = 19)
```

```{r}

bucket_mid <- ( ( (df_conus$lightning - 1) %/% 10 ) * 10 ) + 5
mean_vals <- tapply(df_conus$aod, bucket_mid, mean, na.rm = TRUE)

plot(as.numeric(names(mean_vals)), mean_vals,
     xlab = "Lightning (bucket midpoint)", ylab = "Mean AOD")


```

```{r}
m1 <- lm(lightning ~ aod, data = df_conus)
m2 <- lm(lightning ~ aod + cape, data = df_conus)
m3 <- lm(lightning ~ bc + du + ss + oc + so, data = df_conus)
m4 <- lm(lightning ~ cape, data = df_conus)
m5 <- lm(lightning ~ cape + bc + du + ss + oc, data = df_conus)

```

```{r}
library(GpGp)
g1 <- fit_model(df_conus$lightning, df_conus[,1:2])
g2 <- fit_model(df_conus$lightning, df_conus[,1:2], X = df_conus[,4])
g3 <- fit_model(df_conus$lightning, df_conus[,1:2], X = df_conus[,5:10])
g4 <- fit_model(df_conus$lightning, df_conus[,1:2], X = cbind(df_conus$aod^2, df_conus$aod))


```

# Poisson Regression

```{r}
p1 <- glm(lightning ~ aod, 
                         data = df_conus, 
                         family = poisson(link = "log"))

```

# Negative Binomial Regression

```{r}
library(MASS)
nb1 <- glm.nb(lightning ~ aod, data = df_conus)

```